=== Gwenio/synafis/templates/schemas/config.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "User Configuration",
	"description": "The project user configuration description.",
	"definitions":
	{
		"FilterList":
		{
			"type": "array",
			"title": "Filters",
			"description": "A list of filters to select which build variations an item applies to.",
			"uniqueItems": true,
			"items":
			{
				"type": "object",
				"title": "Filter",
				"description": "A set of conditions paired with the option they must match.",
				"additionalProperties":
				{
					"type": "string",
					"title": "Selector",
					"description": "A name-value pair of a condition ID and an option value, respectively."
				},
				"minProperties": 1
			},
			"default": []
		},
		"Description":
		{
			"type": "string",
			"title": "Description",
			"description": "Optional descriptive text that does not affect the interpretation of the project."
		},
		"ModifierMap":
		{
			"type": "object",
			"title": "Modifier Map",
			"description": "Lists Build Conditions to modify a result based on, applied in the order they appear.",
			"additionalProperties":
			{
				"type": "object",
				"title": "Build Condition",
				"description": "A Build Condition to modify the result by.",
				"additionalProperties":
				{
					"type": "string",
					"title": "Selection Map",
					"description": "Pairs Option IDs with resulting text. Unlisted Options are paired with their own name.",
					"minLength": 1
				},
				"default": {}
			},
			"default": {}
		},
		"Variants":
		{
			"definitions":
			{
				"Description":
				{
					"type": "string",
					"title": "Description",
					"description": "Optional descriptive text that does not affect the interpretation of the project."
				}
			},
			"type": "object",
			"title": "Build Variations",
			"description": "Used to define conditions for different builds.",
			"additionalProperties":
			{
				"type": "object",
				"title": "Build Condition",
				"description": "A condition to filter by when generating different builds.",
				"required": ["options"],
				"properties":
				{
					"description": { "$ref": "#/definitions/Description" },
					"options":
					{
						"type": "array",
						"title": "Options",
						"description": "The options for the condition.",
						"uniqueItems": true,
						"items":
						{
							"type": "string",
							"title": "Option Value",
							"description": "The identifier for an option.",
							"minLength": 1
						}
					}
				}
			}
		}
	},
	"type": "object",
	"properties":
	{
		"$schema":
		{
			"type": "string",
			"title": "JSON Schema",
			"description": "The path for the JSON schema."
		},
		"variants": { "$ref": "#/definitions/Variants" },
		"destinations":
		{
			"type": "object",
			"title": "Output Directories",
			"description": "Provides the directory paths in which to place output files.",
			"additionalProperties":
			{
				"type": "object",
				"title": "Location",
				"description": "A named output location.",
				"properties":
				{
					"root":
					{
						"type": "string",
						"title": "Root Directory",
						"description": "The path to prefix all variation specific paths with.",
						"default": ""
					},
					"filters": { "$ref": "#/definitions/FilterList" },
					"description": { "$ref": "#/definitions/Description" },
					"folders":
					{
						"$ref": "#/definitions/ModifierMap",
						"title": "Path Modifier Map",
						"description": "Appends a folder to the end of root based on the value of each condition listed, in order."
					}
				}
			}
		},
		"extensions":
		{
			"type": "object",
			"title": "File Extensions",
			"description": "Provides the extensions to append to files.",
			"additionalProperties":
			{
				"type": "array",
				"title": "Extension Category",
				"description": "A named file extension category.",
				"items":
				{
					"type": "object",
					"title": "Extension",
					"description": "The extension for matching build variations.",
					"properties":
					{
						"filters": { "$ref": "#/definitions/FilterList" },
						"description": { "$ref": "#/definitions/Description" },
						"value":
						{
							"type": "string",
							"title": "Extention Value",
							"description": "The actual value for the extension.",
							"default": ""
						}
					}
				}
			}
		},
		"products":
		{
			"type": "object",
			"title": "Production Names",
			"description": "Provides names for files created by the build.",
			"additionalProperties":
			{
				"type": "array",
				"title": "Production List",
				"description": "A list of possible productions.",
				"items":
				{
					"type": "object",
					"title": "Production",
					"description": "A named production used to generate output file names.",
					"properties":
					{
						"filters": { "$ref": "#/definitions/FilterList" },
						"description": { "$ref": "#/definitions/Description" },
						"base":
						{
							"type": "string",
							"title": "Base Name",
							"description": "The base file name to add variation specific prefixes and suffixes on to.",
							"default": ""
						},
						"separator":
						{
							"type": "string",
							"title": "Separator",
							"description": "Text to place between elements used to produce the end result.",
							"default": ""
						},
						"prefix": { "$ref": "#/definitions/ModifierMap" },
						"suffix": { "$ref": "#/definitions/ModifierMap" }
					}
				}
			}
		}
	}
}

=== Gwenio/synafis/config.json
{
	"$schema": "./templates/schemas/config.json",
	"variants":
	{
		"build":
		{
			"description": "The build type.",
			"options": [
				"release",
				"debug"
			]
		}
	},
	"destinations":
	{
		"bin": { "root": "bin" },
		"tmp":
		{
			"root": "tmp",
			"folders":
			{
				"target": {},
				"platform": {},
				"build": {}
			}
		}
	},
	"extensions":
	{
		"obj": [
		{
			"filters": [{ "platform": "winapi" }],
			"value": ".obj"
		}],
		"exe": [
		{
			"filters": [{ "platform": "winapi" }],
			"value": ".exe"
		}]
	},
	"products":
	{
		"tester": [
		{
			"filters": [{ "target": "unit" }],
			"base": "tester",
			"separator": "_",
			"prefix": {},
			"suffix": {}
		}]
	}
}
